Now we move from local Docker → ECR → Kubernetes (EKS)

1️⃣ Deployment YAML (ECR Image)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: 650781539051.dkr.ecr.us-east-1.amazonaws.com/my_01/app_01:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80


2️⃣ LoadBalancer Service YAML

apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

What’s Happening Internally
Pod → Pull image from ECR
Service → Creates AWS LoadBalancer (ELB / NLB)
ELB → Routes traffic to Pods

aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 650781539051.dkr.ecr.us-east-1.amazonaws.com/my-app

